apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: django-todos-app
  labels:
    app: postgres-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresdb