apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: django-todos-app
  labels:
    app: app-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: django-todos-application