apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todos-app-deploy
  namespace: django-todos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-todos-application
  template:
    metadata:
      labels:
        app: django-todos-application
    spec:
      containers:
        - image: erikeft/django-todos:v4
          imagePullPolicy: Always
          name: django-todos-app-container
          envFrom:
            - configMapRef:
                name: app-cm
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: api/v1/healthcheck/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10